### ISSUE TITLE
Cartesian (or recursive) Validation on domain.save()

### ISSUE THREAD

**Issue by Trebla7th** [grails/grails-data-mapping#1064]
### Task List

- [ X ] Steps to reproduce provided
- [ N/A ] Stacktrace (if present) provided
- [ X ] Example that reproduces the problem uploaded to Github
- [ X ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Perform .save() on domain object with multiple references

In the example application, we build a reasonable (if unintuitive) structure:

Author has many Books
Author has many Words
Book has many Words
Word belongs To Author (no reference to Book)
WordLink connects two words, (M:M) belongs to Word

After building some author, book and word data, we start linking words.
When we do the first ```link.save()``` the logging (print statements in the validators) show:
```
Validating Book1-8b47
Validating Book2-8b47
Validating TheAuthor-8b47
Validating Book1-8b47
Validating Book2-8b47
Validating TheAuthor-8b47
```

Duplicate validation, but not too excessive...  but as we link more words, validation spirals out of control, by ```link3.save()``` we have:
```
Validating Book1-8b47
Validating TheAuthor-8b47
Validating TheAuthor-8b47
Validating Book2-8b47
Validating TheAuthor-8b47
Validating TheAuthor-8b47
Validating TheAuthor-8b47
Validating Book1-8b47
Validating TheAuthor-8b47
Validating TheAuthor-8b47
Validating Book2-8b47
Validating TheAuthor-8b47
Validating TheAuthor-8b47
Validating TheAuthor-8b47
```

The Author is validated 10 times.  It appears that the link referencing the author is validating the author, then each word that references the author is validating the author, then each word references another link which references the author is validating the author...

The performance here is on O(n^2) complexity, so when building a structure that has hundreds or thousands of word links, saving each one is causing millions of validations.  This appears to be new with GORM 6.1.8 (up from 6.1.3) and/or Grails 3.3.2 (up from 3.2.10)

### Expected Behaviour

Each object in the domain structure should validate a single time

### Actual Behaviour

Each object in the domain structure validates each time it's referenced

### Environment Information

- **Operating System**: OS X High Sierra 10.13.3
- **GORM Version:** 6.1.8.RELEASE
- **Grails Version (if using Grails):** 3.3.2
- **JDK Version:** 1.8.0_91

### Example Application

https://github.com/Trebla7th/unintentional-one-to-many-fetch-and-validate

I apologize for poorly named project, the purpose evolved after I cloned from another issue.

**Comment by danduke** [comment]
This appears to be related to issues #1022 and #1033.  This is causing performance problems that cause grails applications to be effectively unusable for reasonably sized data sets.  Are there any workarounds or fixes planned at this time?

**Comment by jniewerth** [comment]
Yes exactly. This was preventing us from upgrading to Grails 3.
After applying PR #1139 and #1138 our apps perform comparable to Grails 2 again.

**Comment by zyro23** [comment]
i think that the referenced and merged pr #1138 may have led to a undesired side-effect in case the unique constraint triggers an auto-flush which effectively disables the unique constraint validation.

described here: https://github.com/grails/grails-data-mapping/issues/1192#issuecomment-481228706

not sure if the unique constraint should explicitely use `FlushMode.MANUAL` or if the newly introduced dirty-check should be changed?

feedback would be appreciated. if this should be tracked in a separate issue, i can raise one.

thank you!

**Comment by jniewerth** [comment]
I am wondering why the entity is considered unchanged during flush. Perhaps this is the root cause?

**Comment by zyro23** [comment]
good point! i think you may be right. debugged again and what i am seeing is:
* i try to save a new entity instance that violates a unique constraint
* `UniqueConstraint.processValidate` is invoked
* `UniqueConstraint` -> `DirtyCheckable.hasChanged("mySimpleProperty1")` is true because `DirtyCheckable.$changedProperties` is `null`
* `UniqueConstraint` triggers auto-flush during `.get()`
* `ClosureEventTriggeringInterceptor.onSaveOrUpdate` invokes `DirtyCheckable.trackChanges()`
  * https://github.com/grails/grails-data-mapping/blob/v6.1.11/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/support/ClosureEventTriggeringInterceptor.java#L151
* `UniqueConstraint.processValidate` is invoked again
* `UniqueConstraint` -> `DirtyCheckable.hasChanged("mySimpleProperty1")` is now **false** because `DirtyCheckable.$changedProperties` is an empty `Map` (and is **not** `DirtyCheckingSupport.DIRTY_CLASS_MARKER`)

**Comment by jniewerth** [comment]
I suspect this is due to `trackChanges()` is called on the transient instance. Up to this point a transient instance is dirty on any field because `$changedProperties` is null. But the `ClosureEventTriggeringInterceptor.onSaveOrUpdate` calls `trackChanges()` on it resulting in it becoming non-dirty immediately. I think this is the root cause. `trackChanges() ` should not be called on transient instances. Or trackChanges() should detect `this` is a transient instance and put the `DIRTY_CLASS_MARKER` in `$changedproperties`

**Comment by graemerocher** [comment]
The best way to move this forward is come up with a test that reproduces the issue and send a PR we can then look at it. The reason `trackChanges()` is called in `onSaveOrUpdate()` is that at that point the instance has become persistent and we need to track any changes to it.

However it may be the case that for transient instances `trackChanges` should only be activated after validation has occurred.

**Comment by zyro23** [comment]
sample app with a failing test referenced.
```
Unique index or primary key violation: "UKEC88E96C3AE93831135E389F320B_INDEX_1 ON PUBLIC.BOOK(NAME, AUTHOR_ID) VALUES ('book', 1, 1)"; SQL statement:
insert into book (id, version, name, author_id) values (null, ?, ?, ?) [23505-197]

Expected no exception of type 'org.hibernate.exception.ConstraintViolationException' to be thrown, but got it nevertheless
```

**Comment by jniewerth** [comment]
> The reason `trackChanges()` is called in `onSaveOrUpdate()` is that at that point the instance has become persistent and we need to track any changes to it.

When I understand it right onSaveOrUpdate() is fired before the entity is written to database. The dirty checking should track differences between the in-memory-copy and the database state. 

So it should be initialized when objects are loaded from database and not shortly before persisting them. In case of newly created objects dirty checking is inititalized in `doPostInsert`. In case of loaded objects it is initialized in `onPostLoad()`

What is the rationale behind activating dirty checking in `onSaveOrUpdate` ?

**Comment by graemerocher** [comment]
No because with Hibernate once you call `session.persist(obj)` the object becomes managed and is assigned an ID, so if you mutate the object again after saving we have to know if you have made another change

**Comment by jniewerth** [comment]
That would be the case with `save`. But persist does not guarantee to assign an ID immediately. This happens in the deferred flush. 
If we do another modification between the persist and the flush it would be written to database anyways. After the flush the dirty checking gets reset in `postInsert`.

**Comment by graemerocher** [comment]
Actually that is not true, it depends on the ID generation strategy. For MySQL it is indeed the case that the ID is not assigned until the insert happens, but for other ID generation strategies such as sequence it may be assigned immediately.

**Comment by zyro23** [comment]
i tried to come up with a pull-request that adds `dirtyCheckable.markDirty();` after `dirtyCheckable.trackChanges();` here:
* https://github.com/grails/grails-data-mapping/blob/v6.1.11/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/support/ClosureEventTriggeringInterceptor.java#L316
* https://github.com/grails/grails-data-mapping/blob/v6.1.11/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/support/ClosureEventTriggeringInterceptor.java#L323

that happens only if `dirtyCheckingState == null`, so - i think - only for unmanaged/transient instances?  after the save, the dirty-state is reset via `dirtyCheckable.trackChanges();` in `postInsert` anyway.

i hope that approach is reasonable?

however, after adding that and running the sample test case above with it (local `grails-datastore-gorm-hibernate-core-6.1.12.BUILD-SNAPSHOT`), i did immediately run into grails/grails-core#9820.  
```
java.lang.NullPointerException
	at org.hibernate.engine.spi.BatchFetchQueue.removeBatchLoadableEntityKey(BatchFetchQueue.java:147)
```
i think that is unrelated to my change because it happens as well with `6.1.11` and a non-unique constraint violation (e.g. `name = null`). even with both association sides set explicitly and regardless of which side i try to save..

**Comment by graemerocher** [comment]
Yup that is a long standing Hibernate bug that never seems to get resolved and is caused by evicting a object which causes the ID to be null and then a downstream failure

**Comment by jniewerth** [comment]
Your fix would probably resurrect issue #902

**Comment by jniewerth** [comment]
Im am still analysing this in deep and I think a better way to solve that is to remove the `activateDirtyChecking` from `onSaveOrUpdate` and making sure that `activateDirtyChecking` calls `trackChanges()` in any case. I think the only reason for introducing `activateDirtyChecking` in `onSaveOrUpdate` was Issue #902. But that should be solved by calling `trackChanges` in `postInsert` but I am still investigating this.

**Comment by zyro23** [comment]
sounds great, the instant support from all of you is much appreciated!

**Comment by jniewerth** [comment]
Okay I got it working without resurrecting #902. Solution is to remove `activateDirtyChecking()` from `onSaveOrUpdate()` in `ClosureEventTriggeringInterceptor` and replacing `boolean isDirty(..)` in `GrailsEntityDirtinessStrategy` with this version:

```    @Override
    boolean isDirty(Object entity, EntityPersister persister, Session session) {
        !session.contains(entity) || cast(entity).listDirtyPropertyNames().size()>0 || DirtyCheckingSupport.areEmbeddedDirty(GormEnhancer.findEntity(Hibernate.getClass(entity)), entity)
    }
```
So here `cast(entity).hasChanged()` has to be replaced by `cast(entity).listDirtyPropertyNames().size()>0`.

Root cause is that Hibernate has another notion of dirtyness. Newly created objects are not dirty from Hibernates point view. From the DirtyCheckable standpoint they are. This caused issue #902.

Unfortunately I currently do not have the time to prepare a test and a pull request. Could you do that?

**Comment by zyro23** [comment]
i am really not sure if this dirtyness-mismatch between `DirtyCheckable` and hibernate is desirable and if only changing `GrailsEntityDirtinessStrategy.isDirty` is enough or if `findDirty` has to be changed too...

anyway i committed/referenced the proposed change and a test accompanying it. review/feedback would be great before i actually pull-request those. the test fails with gdm `6.1.11` and passes with the changes made. also, #902 still works, i.e. `UuidInsertSpec` still passes.

and then this will still be only one part regarding my unique-violation/auto-flush problem as the next thing is #1185 (NPE with hibernate-5.1, `EntityActionVetoException` with 5.2.13+) :(

**Comment by jniewerth** [comment]
Someone (@graemerocher) has to make a design decision on that mismatch. Should newly created instances considered DirtyCheckable-"changed"? This differs from the hibernate dirtyness concept which only considers entities dirty, that have been loaded and then changed. I find the DirtyCheckable-"changed" concept more reasonable.

**Comment by graemerocher** [comment]
It is not so much a design decision as understanding the implications of the change and the probability of breaking change. My suggestion is a PR to `gorm-hibernate5` with the change and then we can have a look at the implications on the larger test suite. 

I agree that the dirty checking concept to matches Hibernate's however.

**Comment by jniewerth** [comment]
The design decision I was talking about is the following question: Should DirtyCheckable.hasChanged() keep the current behaviour of considering newly created instances as changed. 

I find that reasonable and we are not breaking any code relying on this.

The other option would be to change DirtyCheckable.hasChanged() to closer resemble Hibernates dirtyness concept (new instance are not considered dirty).

**Comment by puneetbehl** [comment]
@zyro23 I am looking into an issue related `AbstractPersistentEventListener` where the changes made in the state of entity are not persisted from the listener. I believe this is due to removing activateDirtyChecking(entity) from ClosureEventTriggeringInterceptor. 

I looked into this issue but failed to understand if the change make any impact. Could you please help me understand the need for this change?

**Comment by zyro23** [comment]
@puneetbehl see the sample app referenced here: https://github.com/grails/grails-data-mapping/issues/1064#ref-commit-348b708 - it failed without the change. problematic behavior outlined here: https://github.com/grails/grails-data-mapping/issues/1064#issuecomment-481593376

bottom line, prior to the change, unique constraint validation did not work properly if the `get` query used by `UniqueConstraint` triggers an auto-flush.

@longwa also reported an undesired side-effect of the merged pr when using generated identifiers. so if the "fix" can be improved - great.
