### ISSUE TITLE
With new dirty checking save() not working properly

### ISSUE THREAD

**Issue by demon101** [grails/grails-data-mapping#1097]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce
create simple domain without dirty checking 
save to DB
update some entity field by domain method
call save

### Expected Behaviour

The updated entity should be saved, version incremented

### Actual Behaviour

Entity not saved.

It happens because of dirty checking. Non changed entities usually not saved. 
New implementation of dirty checking losing updates by methods:

```
class Group {
    String name
    def updateName(){
        name = "Some new name" 
    }
}
```

with hibernateDirtyChecking: true  works well

### Environment Information

- **Operating System**: TODO
- **GORM Version:** 6.1.9
- **Grails Version (if using Grails):** 3.35
- **JDK Version:** TODO

### Example Application

- : see attachment. Run app and call index controller
[test-data.zip](https://github.com/grails/grails-data-mapping/files/1979971/test-data.zip)

**Comment by puneetbehl** [comment]
This is expected behavior, for the internal assignment you should use the setter `setName(...)`. This is more of a documentation issue.

**Comment by demon101** [comment]
@puneetbehl  are you sure about this behavior?
For me as a user I really difficult to understand, why my changes not stored to DB in a simple application without any dirty feature usages.  

For me, it looks like a broken the good old magic

**Comment by puneetbehl** [comment]
Yes, I am sure. The way it works is that the `DirtyCheckingTransformation` modifies all setters of your class so that the dirty checking is tracked per field. Otherwise, Hibernate has to compute if your object is dirty by reading all properties of your class into an in-memory array and then reading them again later and doing a manual diff of each property is very inefficient performance wise.

So, we override the default Hibernate dirty checking strategy which works with `DirtyCheckable` interface and returns property which is actually dirty thus massively improving the GORM update performance.

**Comment by demon101** [comment]
Hm, but in my example no DirtyCheckable interfaces at all. 
I understand, how new implementation works. But I'm telling, with this implementation really simple to create heavily reproducible bug.

**Comment by longwa** [comment]
We came across this today as well and didn't recall seeing it in the documentation anywhere. Definitely caught us by surprise. I agree that this could lead to non-obvious issues.

**Comment by graemerocher** [comment]
It is a trade-off, right now we modify all setters. This has an unfortunate edge case where if you modify a property within the class it sets the field, rather than going through the setter, bypassing change tracking detection. It would be complex and error prone to scan the whole AST looking for cases where you are setting the field and changing them to a setter (the only possible solution).

So right now you have to call `setFoo(..)` internal to the class or call `markDirty(..)`. 

The benefit to users is in performance. By default Hibernate reads all of your properties into an Object[] from your class and then for each `flush()` reads another `Object[]` and does a manual diff of the property values to perform dirty checking. This is horrible from a performance point of view and gets worse the large your classes.

With GORM we track changes to your properties via this AST transformation and this diff is not necessary so update operations are much, much faster.

**Comment by demon101** [comment]
@graemerocher  as a hacky solution internal fields can be renamed during transformation. 

```
class A{
  int fInternal  // before transformation int f

  def setF(int val){
     this.fInternal = 10
  }
   
  int getF(){
    fInternal
  } 

  def update(){
     f = 20 // setF will be used
  } 
} 
```

In this case, even in internal methods getters/setters will be used.

**Comment by puneetbehl** [comment]
@longwa We have updated the documentation around it with a note section **1.2.13. New Dirty Checking Implementation**. You can check the documentation for the snapshot version [here](http://gorm.grails.org/snapshot/hibernate/manual/).

**Comment by tircnf** [comment]
@puneetbehl -- that information is no longer in the snapshot documentation.
Did the need for that setting disappear in gorm 7?

**Comment by puneetbehl** [comment]
@tircnf It looks it is still present in http://gorm.grails.org/6.1.x/hibernate/manual/ .It is removed from 7.0.x as it was the part of "what's new" section in 6.1.x and not new anymore. I think it should be moved to somewhere under the configurations section. 

Please report a new issue and maybe a PR too ;-)
