### ISSUE TITLE
Save without flush does not save in db

### ISSUE THREAD

**Issue by gabivis** [grails/grails-data-mapping#1241]
### Steps to Reproduce

1. Update domain object inside a transactional method
`   @Transactional
     def updateArticleTitle() {
        Article article = Article.findById('12345');
        article.setTitle("myTitle");
        article.save();
}`

### Expected Behaviour

Object should be saved in  the db.

### Actual Behaviour

The object is not saved in db, unless I use save(flush: true).

I am using:
grailsVersion=3.3.9
gormVersion=6.1.11.RELEASE

**Comment by gabivis** [comment]
Hmm, I created a test app from scratch and it is working fine. I will try to see what is different in my actual application and let you know. Thanks.

**Comment by gabivis** [comment]
Ok, so the problem is the config hibernate { flush.mode = 'manual' }.
In grails 2.5.2 saving was done in this case even though we had flush.mode set to manual.
Was this change intentional for grails 3.3.9?

**Comment by ilopmar** [comment]
@gabivis Flush mode was changed in 6.1.x: http://gorm.grails.org/6.1.10/hibernate/manual/index.html#_flush_mode_now_commit_by_default

**Comment by gabivis** [comment]
> @gabivis Flush mode was changed in 6.1.x: http://gorm.grails.org/6.1.10/hibernate/manual/index.html#_flush_mode_now_commit_by_default

Thanks @ilopmar. Yeah, I saw that the default flush mode has changed from AUTO to COMMIT. However, in my project flush.mode was set to manual, and saving was done to db in grails 2.5.2 but it is not done in grails 3.3.9;

**Comment by zyro23** [comment]
i would guess it worked before because springs `HibernateTransactionManager` changes flush mode to auto for transactions with pre-bound sessions that use flush mode manual. `GrailsHibernateTransactionManager` does not do that (or rather overrides it with the default flush mode again).

it would be great to see this behavior being configurable. a combination of flush mode manual outside transactions and auto or commit within transactions is really useful.

* https://github.com/spring-projects/spring-framework/blob/v5.1.6.RELEASE/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTransactionManager.java#L513-L520
* https://github.com/grails/gorm-hibernate5/blob/v7.0.0/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/GrailsHibernateTransactionManager.groovy#L74-L77

**Comment by jameskleeh** [comment]
"lush mode manual outside transactions" You can't do writes outside of a transaction in Hibernate 5.4+, so this won't apply with GORM 7. I think the current behavior as described is correct so I'll close this issue.

**Comment by gabivis** [comment]
> "lush mode manual outside transactions" You can't do writes outside of a transaction in Hibernate 5.4+, so this won't apply with GORM 7. I think the current behavior as described is correct so I'll close this issue.

I'm not sure I follow the quote "flush mode manual outside transactions". My code is executing inside a transaction. The method has the @Transactional annotation.
