### ISSUE TITLE
Grails <= 4.0.2 Unexpected autotrimming values during saving but not during findingBy

### ISSUE THREAD

**Issue by majkelo** [grails/grails-data-mapping#1281]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Create any domain class (eg `Spaced` ) with unique constraint on String value (eg description). Checkk out: https://github.com/majkelo/grails402autotrimmingissue/commit/f04b9304adfddfcb875fbd1f0f39a52231905dbc

If you try to run 

```
Spaced.findOrCreateByDescription(' withPrecedingSpace').save()
Spaced.findOrCreateByDescription(' withPrecedingSpace').save() // this will throw an exception, cause instance was not found and is not able to save it neither because of unique constraint

```

### Expected Behaviour

Not sure why are we triming data passed to save and we are not triming data when looking for data. It's inconsistient behaviour and could cause unexpected problems

### Actual Behaviour

Not sure why are we triming value during saving, but not during dynamic findBy...(...) or findWhere(...). 
Using findOrCreate(...) is pointless here, cause we won't find a proper instance and won't be able to save the data, because constraint unique is used.

### Environment Information

- **Operating System**: Pop OS
- **Grails Version:** 4.0.2 and 4.0.1
- **JDK Version:** 11.0.5-open for Grails 4.0.2 and 8.0.232-open for Grails 4.0.1
- **Container Version (If Applicable):** -

### Example Application

https://github.com/majkelo/grails402autotrimmingissue

**Comment by puneetbehl** [comment]
I believe it is happening because of GrailsWebDataBinder which tries to bind the `description` property with `Spaced` instance in case it is not found in the database. See https://github.com/grails/grails-core/blob/4.0.x/grails-web-databinding/src/main/groovy/grails/web/databinding/GrailsWebDataBinder.groovy#L564

But, the GrailsWebDatabinder is not involved when finding the instance from the database as we pass the description to the query. 

I think you should be able to disable trimming for the GrailsWebDataBinder by setting following in application.yml: 
```
grails.databinding.trimStrings: false
```
See https://docs.grails.org/latest/guide/theWebLayer.html#dataBinding for more details.
