### ISSUE TITLE
GPMONGODB-368: Records for subclassed domains no longer getting '_class' property

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#334]
Original Reporter: aeischeid
Environment: Ubuntu, grails 2.3.7, mongo 2.4
Version: 3.0.1
Migrated From: http://jira.grails.org/browse/GPMONGODB-368

we have a Certificate domain and it is extended by various certificate types. Using the 1.3 line of the plugin each document inserted to mongo would get a '_class' property added to it and presumably something like CertTypeA.findAllByName(name) would use that property to complete the query successfully. 

With 2.0.1 writes seem to work fine except for the '_class' is absent and thus queries on the subclass domains fail to return anything...

**Comment by mikedehaan** [comment]
I had this issue which turned out to be caused by a developer using an undeclared field on the domain object. For example, given a domain object:

class MyDomainObject {
    String field;
}

The problem occurred when setting the value of an undeclared field:

MyDomainObject obj = new MyDomainObject();

obj.field = "This works"
obj.nonExistantField = new BigDecimal("0.0"); // This saves, but _class is no longer set
obj.save();

For me, this gave the above problem and later gave an exception saying "cannot serialize BigDecimal". Something about referencing that undeclared field bumped the object out of GORM proper and removed the Spring converters (and other logic such as _class).

A proper error message would have helped track this down. Fixing reference to the undeclared variable seemed to have solved the issue.
