### ISSUE TITLE
GORM autoTimestamp features do not work when dynamicUpdate is set to on in mappings

### ISSUE THREAD

**Issue by davydotcom** [grails/grails-data-mapping#729]
It seems the autoTimestamp feature does not work on dynamic updates in grails 3.1.8

A test project can be found here with 3 domain class test scenarios (integration tests)

https://github.com/davydotcom/autotimestamp-test

**Comment by davydotcom** [comment]
One addendum test was added `TestC.where{...}.updateAll(name:'blah')` also does not update lastUpdated

**Comment by graemerocher** [comment]
That is not a regression and has always been the case. Batch updates don't update `lastUpated` automatically, you would have to do that manually.

**Comment by davydotcom** [comment]
Agreed its not a regression, but seems odd. Why would a batch update not
mean auto timestamps since the record was modified does it not make since
to populate the field?

**Comment by davydotcom** [comment]
Just seems like an unnecessary gotya in GORM thats easy to fix so I tossed
it out there

**Comment by graemerocher** [comment]
So the last update problem with dynamic updates is not a regression either and the behaviour is definitely very old. The issue is because Hibernate works out the dirty properties prior to sending the `preUpdate` event and even if you change `lastUpdated` it is not regarded as dirty. I don't see us being to fix this for 5.0.x

It may be possible to fix this in the future if we implement our own custom dirty checking (which we already do with the `DirtyCheckable` trait etc.) that is wired into Hibernate. See #740

**Comment by graemerocher** [comment]
I did however fix the issue with `updateAll` and `lastUpdated`

**Comment by davydotcom** [comment]
I was able to bandaid this to work using a PersistentEventListener preSave event:

```
	void preSave(final AbstractPersistenceEvent event) {
		if(!event?.entityObject) {
			return
		}
		if(event.entityObject.dirtyPropertyNames?.size() > 0) {
			def domainArtefact = getDomainArtefact(event.entityObject.getClass().name)
			if(domainArtefact.hasProperty('lastUpdated')) {
				event.entityObject.lastUpdated = new Date()
			}
		}
	}
```

**Comment by graemerocher** [comment]
With #740 resolved we can potentially resolve this now
