### ISSUE TITLE
Problem with Transactional on both Controller and Service in combination with multi-tenancy

### ISSUE THREAD

**Issue by goeh** [grails/grails-data-mapping#767]
Grails 3.2.0.M2

```
grails.gorm.multiTenancy.mode: DISCRIMINATOR
```

If I have a controller action marked as @Transactional that calls a service marked as @Transactional and I do this inside a withCurrent{ ... } multi-tenant block I get an exception.

```
org.springframework.transaction.IllegalTransactionStateException: Pre-bound JDBC Connection found!
HibernateTransactionManager does not support running within DataSourceTransactionManager if told to manage the DataSource itself.
```

I have a test application here https://github.com/goeh/grails-session-issue

Please look in https://github.com/goeh/grails-session-issue/blob/master/grails-app/controllers/session/issue/PersonController.groovy for code examples.

When running the integration test I get another exception:

```
ERROR org.springframework.transaction.support.TransactionSynchronizationUtils -
    TransactionSynchronization.beforeCompletion threw exception
    org.hibernate.SessionException: Session is closed!
        at org.hibernate.internal.AbstractSessionImpl.errorIfClosed(AbstractSessionImpl.java:132)
        at org.hibernate.internal.SessionImpl.disconnect(SessionImpl.java:510)
        at org.springframework.orm.hibernate5.SpringSessionSynchronization.beforeCompletion(SpringSessionSynchronization.java:123)
```

**Comment by graemerocher** [comment]
The issue here is you are trying to call a service that uses `@Transactional`, which is not multi-tenant aware and is going to use the default connection. The `withCurrent` method will bind a session for a different session factory and JDBC connection based on the tenant id and then `@Transactional` comes along and tries to bind the default connection and fails . 

Running `@Transactional` services within tenant id blocks won't be supported in the first version of GORM multi-tenancy and the solution is to remove the `@Transactional` annotation and use `withTransaction` which is tenant id aware.

In order for this to be made to work Grails core and the `@Transactional` AST transformation have to be altered to be made multi-tenant aware. A new set of multi-tenant aware transforms in scheduled for the GORM 6.1 timeframe.

In the meantime users should avoid mixing `@Transactional` and multi-tenancy.

The `Session is closed!` error was different bug and is fixed in master.

**Comment by goeh** [comment]
Ok I understand. But it's a major limitation because I might not know what other service calls my code will trigger, and those services might use `@Transactional`. I'm thinking about plugins, etc.
But I guess that multi-tenancy is a major thing for Grails 3.2 and beyond so plugins you use must be multi-tenant aware. You cannot just pull in any plugin and hope it will work with multi-tenancy. I guess that's understandable.
I will replace `@Transactional` with withCurrent and see how it goes. Thanks.

**Comment by graemerocher** [comment]
We are aware it is limitation, that is why it is on the roadmap for GORM 6.1

First we need to supply a stable multi-tenancy implementation at the GORM level, and then we can implement additional features like changing how `Transactional` works on the Grails side.

**Comment by yakoob** [comment]
please fix...
