### ISSUE TITLE
NPE on save with validation errors

### ISSUE THREAD

**Issue by jameskleeh** [grails/grails-data-mapping#887]
Example project: https://github.com/jameskleeh/test-domain-save-npe

To reproduce: `./gradlew bootRun`

The bootstrap is adding to a one to many with invalid properties in the map. (`title: ...` should be `name: ...`)

Expected behavior:
The domain simply fails to validate and no NPE is thrown

**Comment by graemerocher** [comment]
The reason for this is `Album` doesn't belong to `Artist`, hence we don't cascade validation. I can think of a few possible solutions:

1. Add validation check if the association doesn't cascade to `addToAlbums` that marks the object being added to as invalid of the passed object is invalid
2. Inside the `flush()` if an object is invalid throw a validation exception. Since we know Hibernate doesn't handle eviction of changes well, is it worth continuing to allow it it to possibly throw a NPE?

**Comment by graemerocher** [comment]
Root cause issue https://hibernate.atlassian.net/projects/HHH/issues/HHH-11721

**Comment by graemerocher** [comment]
Duplicate https://github.com/grails/grails-core/issues/10604
