### ISSUE TITLE
Dynamic finder not found on version 6.1

### ISSUE THREAD

**Issue by mburak** [grails/grails-data-mapping#894]
I installed the latest 6.1 version and the application is not compiling anymore.
It seems that it's trying to do some static check and it's not finding the finders for certain domains. Going back to 6.0.9 makes it work again.
This is the error: 
```
/Users/matias/Sites/app/6.x/platform/grails-app/domain/com/app/platform/core/DataSet.groovy: 140: [Static type checking] - Cannot find matching method com.app.platform.apps.Application#findByDescription(java.lang.String). Please check if the declared type is right and if the method exists.
 @ line 140, column 23.
               __app__ = Application.findByDescription(__appName__)
                         ^

1 error
```

This is called from a getter in some domain, and Application is another domain object.
Any ideas of what could be changed?

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by mburak** [comment]
You can see the behavior in this project: https://github.com/mburak/sampleapp just by downloading it and doing "grails compile"

**Comment by graemerocher** [comment]
This was fixed by https://github.com/grails/grails-data-mapping/commit/61cad96f6e725db5a569e9c3041cf6791d6c2509

However, I feel I should point out that it would not have been an issue if you were using correct coding style in your codebase. The use of underscores before and after property names and weird programming syntax not typically used in any Groovy/Java code standards violates the java bean convention for properties, and is the root cause of the error.

**Comment by mburak** [comment]
Yes, you are totally right. This was a kind of edge case that we need to review.
Thank you.
