### ISSUE TITLE
rx-gorm-rest applied as mentioned in documentation doesn't work

### ISSUE THREAD

**Issue by rahulsom** [grails/grails-data-mapping#899]
I used Grails 3.2.8 - (grails create-app with rest-api profile). I also did the same thing with IntelliJ's support for directly creating a grails application.

Creating an application that way puts `gormVersion=6.0.9.RELEASE` into the `gradle.properties`.

When trying to add rx-gorm-rest like below, the dependency is not configured correctly.

```groovy
dependencies {
    compile 'org.grails.plugins:rx-gorm-rest-client:1.1.0'
}
```

`1.1.0` does not exist on `repo.grails.org`. `1.1.0.RELEASE` does. So I used that.

Grails tries to download `org.grails:grails-datastore-gorm-rx-rest-client` with version `6.0.9.RELEASE`.

Removing that line from `gradle.properties` fixes it.

If you can advise me how this needs to be fixed, I'll send a PR.

## Steps to reproduce:

1. Run this
   ```bash
   grails create-app demo --profile rest-api
   ```
2. Add this dependency to `build.gradle`
   ```groovy
   compile 'org.grails.plugins:rx-gorm-rest-client:1.1.0.RELEASE'
   ```
3. Run `./grailsw run-app`

**Comment by graemerocher** [comment]
Set `gormVersion=6.1.0.RELEASE` as well

**Comment by rahulsom** [comment]
@graemerocher, on doing that, I get this

```
| Resolving Dependencies. Please wait...
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'demo'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not find org.grails:grails-datastore-gorm-rx-rest-client:6.1.0.RELEASE.
     Searched in the following locations:
         file:/Users/rxs6995/.m2/repository/org/grails/grails-datastore-gorm-rx-rest-client/6.1.0.RELEASE/grails-datastore-gorm-rx-rest-client-6.1.0.RELEASE.pom
         file:/Users/rxs6995/.m2/repository/org/grails/grails-datastore-gorm-rx-rest-client/6.1.0.RELEASE/grails-datastore-gorm-rx-rest-client-6.1.0.RELEASE.jar
         https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-rx-rest-client/6.1.0.RELEASE/grails-datastore-gorm-rx-rest-client-6.1.0.RELEASE.pom
         https://repo.grails.org/grails/core/org/grails/grails-datastore-gorm-rx-rest-client/6.1.0.RELEASE/grails-datastore-gorm-rx-rest-client-6.1.0.RELEASE.jar
     Required by:
         project : > org.grails.plugins:rx-gorm-rest-client:1.0.5.RELEASE
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
CONFIGURE FAILED
```

**Comment by johnkeates** [comment]
Same story here, but now there is no way to make this work at all. org.grails:grails-datastore-gorm-rx-rest-client:6.1.0.RELEASE obviously doesn't exist, hell, any version above 1.1.0 doesn't exist. It seems to me a variable for the version is being put somewhere where it doesn't belong.

I'm not sure how to make this work at this time, older versions have the same issue. It's as if rx-gorm-rest-client is completely unusable at this point. Removing the variable or setting it to a slightly different version constantly makes something not match. 

Setting the variable to null gives problems, removing it gives problems, setting it to 1.1.0 doesn't work since the gorm versions are much higher than that, but setting it to any 6.x breaks grails-datastore-gorm-rx-rest-client because that hasn't even gone beyond 2.x yet.

**Comment by graemerocher** [comment]
This is a bug in the Grails gradle plugin. Can be worked around by defining the following in your `build.gradle`:

```groovy
configurations.all {
    resolutionStrategy.eachDependency { details ->
        if(details.requested.name == 'grails-datastore-gorm-rx-rest-client') {
            details.useVersion("1.1.0.RELEASE")
        }
    }
}
dependencies {
    ...
} 
```

**Comment by johnkeates** [comment]
Excellent, thank you very much!
