### ISSUE TITLE
Statement batch of session not cleared on transaction rollback

### ISSUE THREAD

**Issue by bassmartin** [grails/grails-data-mapping#991]
### Overview

I'm using Spring Retry to re-attempt transactions of a REST endpoint (mainly to retry when there is a StaleStateException).

When a StaleStateException happens on the first attempt of the transaction to modify the name of a Person domain instance, there is a statement batch with the failing update SQL that gets linked to the Hibernate Session injected in the controller's action.

On subsequent attempts (that should successfully update the Person instance since the instance is reloaded from the DB), it fails during commit since the old update statement is still in the statement batch associated to the Session.

### Steps to Reproduce

1. Run teststatementbatch.PersonServiceIntegrationSpec of the provided example
2. Look at the printed logs for the exception thrown during the commit

### Expected Behaviour

I would expect that the transaction rollback that is happening on the first attempt to update the name of the Person would clear the Session (as it does) and also the associated statement batch so that the second attempt to update the Person's name works.

### Actual Behaviour

The statement batch associated to the Hibernate session is not cleared so any further attempt to commit a change to Person fails

### Environment Information

- **Operating System**: OSX
- **GORM Version:** 6.0.12.RELEASE
- **Grails Version (if using Grails):** 3.2.11
- **JDK Version:** jdk1.8.0_111

### Example Application

https://github.com/bassmartin/statement_batch_not_cleared_example

**Comment by zyro23** [comment]
i can confirm this. and it is a critical issue for applications that retry, e.g. on `OptimisticLockingException`.

spring-retry can be ruled out as a source of the problem. same result using a try-catch cascade manually instead of `@Retryable`.
also, do not get confused by the output showing 3 retries ("pass 3") - that is because spring-retry defaults to `@Retryable.maxAttempts = 3`

adding this snippet to the top of the `updateName` service method shows the problem with the statement batch:

```groovy
Person.withSession {
    println it.jdbcCoordinator.currentBatch?.statement
}
```
output:
```
pass 1

null

commit

2017-08-24 08:09:34.089 ERROR --- [o-auto-1-exec-3] org.hibernate.internal.SessionImpl       : HHH000346: Error during managed flush [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]

pass 2

[update person set version=?, name=? where id=? and version=?:org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy[Proxy=968291492; Query=update person set version=?, name=? where id=? and version=?; Delegate=null]]

commit

2017-08-24 08:09:35.118 ERROR --- [o-auto-1-exec-3] org.hibernate.internal.SessionImpl       : HHH000346: Error during managed flush [null]
```
"pass 2" should imho not have the update statement in its jdbc statement batch because that one comes from "pass 1" and was rolled back.

i also tried hibernate-5.2.10.Final with gorm-6.1.6. exact same behavior/error.

this hibernate issue looks like it could be related, especially if you take a look at the fix in the pull-request?
* https://hibernate.atlassian.net/browse/HHH-11732
* https://github.com/hibernate/hibernate-orm/pull/1907/files#diff-9f50b411561c96be73412c094a0bfc5eR297

**Comment by graemerocher** [comment]
So there appear to be two possible current workarounds. One is the configuration in `application.yml`:

```yaml
hibernate:
    jdbc:
      batch_versioned_data: false
```

That disables the batching thus avoiding the stale cached batch data problem. Another option is the disable OSIV so a fresh session is used for each retry:

```yaml
hibernate:
    osiv:
      enabled: false
```

I am still investigating whether a solution is possible when `batch_versioned_data` is `true`

**Comment by zyro23** [comment]
@graemerocher cool! nice one. i like `hibernate.jdbc.batch_versioned_data = false`.

seems like one more potentially-breaking change that comes with hibernate-5.

https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html
>Some JDBC drivers return incorrect row counts when a batch is executed. If your JDBC driver falls into this category this setting should be set to false. Otherwise, it is safe to enable this which will allow Hibernate to still batch the DML for versioned entities and still use the returned row counts for optimistic lock checks. Since 5.0, it defaults to true. Previously (versions 3.x and 4.x), it used to be false.

**Comment by bassmartin** [comment]
Wow, that was a quick guys! Thank you!
